#!/bin/bash

set -euo pipefail

usage() {
    echo "Usage: $0 [keys_dir] [output_file] [cloud_init_ssh_file]"
    echo "Defaults:"
    echo "  keys_dir=~/keys"
    echo "  output_file=~/auth.keys"
    echo "  cloud_init_ssh_file=~/configs/common/ssh-authorized-keys.yaml"
}

if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ]; then
    usage
    exit 0
fi

KEYS_DIR="${1:-$HOME/keys}"
OUTPUT_FILE="${2:-$HOME/auth.keys}"
CLOUD_INIT_SSH_FILE="${3:-$HOME/configs/common/ssh-authorized-keys.yaml}"

if [ ! -d "${KEYS_DIR}" ]; then
    echo "Keys directory not found: ${KEYS_DIR}"
    exit 1
fi

shopt -s nullglob
pub_files=("${KEYS_DIR}"/*.pub)

if [ "${#pub_files[@]}" -eq 0 ]; then
    echo "No .pub files found in ${KEYS_DIR}"
    exit 1
fi

tmp_file="$(mktemp)"
trap 'rm -f "${tmp_file}"' EXIT

for file in "${pub_files[@]}"; do
    if [ ! -f "${file}" ]; then
        continue
    fi

    echo "Adding ${file}"
    cat "${file}" >> "${tmp_file}"
done

mkdir -p "$(dirname "${OUTPUT_FILE}")"
awk 'NF && !seen[$0]++' "${tmp_file}" > "${OUTPUT_FILE}"

mkdir -p "$(dirname "${CLOUD_INIT_SSH_FILE}")"
{
    echo "# Generated by combine-keys.sh"
    echo "ssh_authorized_keys:"

    while IFS= read -r key_line; do
        escaped_key="$(printf '%s' "${key_line}" | sed "s/'/''/g")"
        printf "  - '%s'\n" "${escaped_key}"
    done < "${OUTPUT_FILE}"
} > "${CLOUD_INIT_SSH_FILE}"

echo "Wrote combined keys to ${OUTPUT_FILE}"
echo "Total unique keys: $(wc -l < "${OUTPUT_FILE}")"
echo "Wrote cloud-init SSH section to ${CLOUD_INIT_SSH_FILE}"